/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.mwengine;

public class ADSR {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ADSR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ADSR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_ADSR(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ADSR() {
    this(MWEngineCoreJNI.new_ADSR(), true);
  }

  public ADSR clone() {
    long cPtr = MWEngineCoreJNI.ADSR_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ADSR(cPtr, false);
  }

  public void cloneEnvelopes(ADSR source) {
    MWEngineCoreJNI.ADSR_cloneEnvelopes(swigCPtr, this, ADSR.getCPtr(source), source);
  }

  public void setBufferLength(int bufferLength) {
    MWEngineCoreJNI.ADSR_setBufferLength(swigCPtr, this, bufferLength);
  }

  public int getBufferLength() {
    return MWEngineCoreJNI.ADSR_getBufferLength(swigCPtr, this);
  }

  public float getAttack() {
    return MWEngineCoreJNI.ADSR_getAttack(swigCPtr, this);
  }

  public float getDecay() {
    return MWEngineCoreJNI.ADSR_getDecay(swigCPtr, this);
  }

  public float getSustain() {
    return MWEngineCoreJNI.ADSR_getSustain(swigCPtr, this);
  }

  public float getRelease() {
    return MWEngineCoreJNI.ADSR_getRelease(swigCPtr, this);
  }

  public void setAttack(float aValue) {
    MWEngineCoreJNI.ADSR_setAttack(swigCPtr, this, aValue);
  }

  public void setDecay(float aValue) {
    MWEngineCoreJNI.ADSR_setDecay(swigCPtr, this, aValue);
  }

  public void setSustain(float aValue) {
    MWEngineCoreJNI.ADSR_setSustain(swigCPtr, this, aValue);
  }

  public void setRelease(float aValue) {
    MWEngineCoreJNI.ADSR_setRelease(swigCPtr, this, aValue);
  }

  public SWIGTYPE_p_SAMPLE_TYPE getLastEnvelope() {
    return new SWIGTYPE_p_SAMPLE_TYPE(MWEngineCoreJNI.ADSR_getLastEnvelope(swigCPtr, this), true);
  }

  public void setLastEnvelope(SWIGTYPE_p_SAMPLE_TYPE lastEnvelope) {
    MWEngineCoreJNI.ADSR_setLastEnvelope(swigCPtr, this, SWIGTYPE_p_SAMPLE_TYPE.getCPtr(lastEnvelope));
  }

  public SWIGTYPE_p_SAMPLE_TYPE apply(SWIGTYPE_p_AudioBuffer inputBuffer) {
    return new SWIGTYPE_p_SAMPLE_TYPE(MWEngineCoreJNI.ADSR_apply__SWIG_0(swigCPtr, this, SWIGTYPE_p_AudioBuffer.getCPtr(inputBuffer)), true);
  }

  public SWIGTYPE_p_SAMPLE_TYPE apply(SWIGTYPE_p_AudioBuffer inputBuffer, int eventOffset) {
    return new SWIGTYPE_p_SAMPLE_TYPE(MWEngineCoreJNI.ADSR_apply__SWIG_1(swigCPtr, this, SWIGTYPE_p_AudioBuffer.getCPtr(inputBuffer), eventOffset), true);
  }

}
