/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.mwengine;

public class AllPassDelay {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AllPassDelay(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AllPassDelay obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_AllPassDelay(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AllPassDelay() {
    this(MWEngineCoreJNI.new_AllPassDelay(), true);
  }

  public void delay(float aDelay) {
    MWEngineCoreJNI.AllPassDelay_delay(swigCPtr, this, aDelay);
  }

  public float update(float aSample) {
    return MWEngineCoreJNI.AllPassDelay_update(swigCPtr, this, aSample);
  }

}
