/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.mwengine;

public class LFO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_LFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LFO() {
    this(MWEngineCoreJNI.new_LFO(), true);
  }

  public static double MAX_LFO_RATE() {
    return MWEngineCoreJNI.LFO_MAX_LFO_RATE();
  }

  public static double MIN_LFO_RATE() {
    return MWEngineCoreJNI.LFO_MIN_LFO_RATE();
  }

  public float getRate() {
    return MWEngineCoreJNI.LFO_getRate(swigCPtr, this);
  }

  public void setRate(float value) {
    MWEngineCoreJNI.LFO_setRate(swigCPtr, this, value);
  }

  public int getWave() {
    return MWEngineCoreJNI.LFO_getWave(swigCPtr, this);
  }

  public void setWave(int value) {
    MWEngineCoreJNI.LFO_setWave(swigCPtr, this, value);
  }

  public void generate() {
    MWEngineCoreJNI.LFO_generate(swigCPtr, this);
  }

  public SWIGTYPE_p_WaveTable getTable() {
    long cPtr = MWEngineCoreJNI.LFO_getTable(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_WaveTable(cPtr, false);
  }

}
