/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class BitCrusher extends BaseProcessor {
  private transient long swigCPtr;

  protected BitCrusher(long cPtr, boolean cMemoryOwn) {
    super(MWEngineCoreJNI.BitCrusher_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BitCrusher obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_BitCrusher(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BitCrusher(float amount, float inputMix, float outputMix) {
    this(MWEngineCoreJNI.new_BitCrusher(amount, inputMix, outputMix), true);
  }

  public float getAmount() {
    return MWEngineCoreJNI.BitCrusher_getAmount(swigCPtr, this);
  }

  public void setAmount(float value) {
    MWEngineCoreJNI.BitCrusher_setAmount(swigCPtr, this, value);
  }

  public float getInputMix() {
    return MWEngineCoreJNI.BitCrusher_getInputMix(swigCPtr, this);
  }

  public void setInputMix(float value) {
    MWEngineCoreJNI.BitCrusher_setInputMix(swigCPtr, this, value);
  }

  public float getOutputMix() {
    return MWEngineCoreJNI.BitCrusher_getOutputMix(swigCPtr, this);
  }

  public void setOutputMix(float value) {
    MWEngineCoreJNI.BitCrusher_setOutputMix(swigCPtr, this, value);
  }

  public void process(SWIGTYPE_p_AudioBuffer sampleBuffer, boolean isMonoSource) {
    MWEngineCoreJNI.BitCrusher_process(swigCPtr, this, SWIGTYPE_p_AudioBuffer.getCPtr(sampleBuffer), isMonoSource);
  }

  public boolean isCacheable() {
    return MWEngineCoreJNI.BitCrusher_isCacheable(swigCPtr, this);
  }

}
