/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class MWEngineCore implements MWEngineCoreConstants {
  public static SWIGTYPE_p_int new_int_array(int nelements) {
    long cPtr = MWEngineCoreJNI.new_int_array(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_int_array(SWIGTYPE_p_int ary) {
    MWEngineCoreJNI.delete_int_array(SWIGTYPE_p_int.getCPtr(ary));
  }

  public static int int_array_getitem(SWIGTYPE_p_int ary, int index) {
    return MWEngineCoreJNI.int_array_getitem(SWIGTYPE_p_int.getCPtr(ary), index);
  }

  public static void int_array_setitem(SWIGTYPE_p_int ary, int index, int value) {
    MWEngineCoreJNI.int_array_setitem(SWIGTYPE_p_int.getCPtr(ary), index, value);
  }

  public static void init() {
    MWEngineCoreJNI.init();
  }

  public static void start() {
    MWEngineCoreJNI.start();
  }

  public static void stop() {
    MWEngineCoreJNI.stop();
  }

  public static void reset() {
    MWEngineCoreJNI.reset();
  }

  public static ProcessingChain getMasterBusProcessors() {
    long cPtr = MWEngineCoreJNI.getMasterBusProcessors();
    return (cPtr == 0) ? null : new ProcessingChain(cPtr, false);
  }

  public static void set_sampleMap(SWIGTYPE_p_std__mapT_std__string_cachedSample_t value) {
    MWEngineCoreJNI._sampleMap_set(SWIGTYPE_p_std__mapT_std__string_cachedSample_t.getCPtr(value));
  }

  public static SWIGTYPE_p_std__mapT_std__string_cachedSample_t get_sampleMap() {
    long cPtr = MWEngineCoreJNI._sampleMap_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__mapT_std__string_cachedSample_t(cPtr, false);
  }

}
